chore: Update docker compose and fix callback url issues

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,41 +1,61 @@
-FROM node:18-slim AS builder
+FROM node:18-slim AS base
 
-# For compatibility with M1 Macs
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apt-get update && \
     apt-get install -y procps && \
     apt-get install -y openssl && \
     apt-get install -y libc6
 
-# Create app directory
 WORKDIR /app
 
-# npm install files
-COPY package*.json pnpm-lock.yaml ./
-COPY prisma ./app/prisma/
-
-# Install app dependencies
-RUN npm install --production --legacy-peer-deps
-
-COPY . .
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 RUN npx prisma generate
-RUN npm run build
 
-FROM node:18-slim
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
-RUN apt-get update && \
-    apt-get install -y procps && \
-    apt-get install -y openssl && \
-    apt-get install -y libc6
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
+RUN yarn build
 
-ENV NODE_ENV production
+# If using npm comment out above and use below instead
+# RUN npm run build
 
+# Production image, copy all the files and run next
+FROM base AS runner
 WORKDIR /app
 
-COPY --from=builder /app/node_modules ./node_modules
-COPY --from=builder /app/package.json ./
-COPY --from=builder /app/next.config.js ./
-COPY --from=builder /app/.next ./.next
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
 COPY --from=builder /app/public ./public
 
-CMD npm run start -- -p 3001
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder /app/node_modules ./node_modules
+COPY --from=builder /app/package.json ./
+COPY --from=builder /app/.next ./.next
+COPY --from=builder /app/next.config.js ./next.config.js
+COPY --from=builder /app/prisma ./prisma
+
+EXPOSE 3001
+
+ENV PORT 3001
+
+CMD ["yarn", "start"]
